In [2]:
import numpy as np
a = np.array([1,2,3,4,5,6])
b = a[3:]
print(f'b={b}')
b[1] = 15
print(f'b={b}')
print(f'a={a}')

b=[4 5 6]
b=[ 4 15  6]
a=[ 1  2  3  4 15  6]


In [3]:
c = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(f'c.shape={c.shape}, c.ndim={c.ndim}')
print(f'c={c}')
print(f'c[2,3]={c[2,3]}')

c.shape=(3, 4), c.ndim=2
c=[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
c[2,3]=12


In [4]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])
print(f'ndim={array_example.ndim}, size={array_example.size}, shape={array_example.shape}')

ndim=3, size=24, shape=(3, 2, 4)


In [8]:
ones = np.ones((4, 3, 2))
print(ones.shape)
print(ones)

(4, 3, 2)
[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [9]:
# Create a 3D array with distinct values to see the order
# (2 pages, 2 rows, 2 columns)
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print("The 3D Array:")
print(arr)

print("\nThe Flattened (Memory) Order:")
print(arr.flatten())

The 3D Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

The Flattened (Memory) Order:
[1 2 3 4 5 6 7 8]
